Plat 9575 update bug snag casing in unity plugin UI
bugsnag/bugsnag-unity pull request #694
Opened 2023-02-06 16:27 UTC by clr182

## Goal

Update from old branding (Bugsnag) to new branding (BugSnag)

## Changeset

Ui Elements were updated to keep inline with BugSnags new branding

## Testing

Tested changes by importing package into the new unity project

2023-02-08 17:20 UTC, clr182 commented
Sub task PR: https://github.com/bugsnag/dashboard-js/pull/7093

2023-02-14 09:59 UTC, richardelms requested changes

2023-02-14 09:59 UTC, richardelms commented on features/fixtures/maze_runner/Assets/Scripts/Scenarios/Csharp/Config/IsStarted.cs
> +﻿using System.Collections;
Why is the IsStarted stuff in this PR?

2023-02-14 09:59 UTC, richardelms commented on upm-tools/AssemblyDefinitions/Bugsnag.asmdef
>  ﻿{
if you didnt already, please follow the steps in the CONTRIBUTING.md to build a local UPM package and check that this change doesnt break the package

2023-02-14 09:59 UTC, richardelms commented on upm-tools/AssemblyDefinitions/BugsnagEditor.asmdef
>  {
if you didnt already, please follow the steps in the CONTRIBUTING.md to build a local UPM package and check that this change doesnt break the package

2023-03-01 14:11 UTC, closed without merging